version: '3'
services:
  user: 
    build: .
    ports:
      - 8080:80
    networks:
      cstmnetwork:
        ipv4_address: 172.20.0.10

networks:
  cstmnetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16